language: node_js
sudo: required
node_js:
  - '9'
addons:
  sauce_connect: true
script:
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then npm run test'
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then npm run sauceLabs'
